name: jci_worldcon_customer
description: "JCI WorldCon Customer - A Flutter project for Customer side of JCI WorldCon App "
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  get: ^4.7.2
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
